fullnameOverride: endorser

replicaCount: 1

podAnnotations:
  sidecar.istio.io/proxyCPU: 10m
  ad.datadoghq.com/endorser.logs: >-
    [{
      "source": "python.uvicorn",
      "service": "endorser",
      "log_processing_rules": [{
        "type": "exclude_at_match",
        "name": "exclude_health_probes",
        "pattern": "GET /health/(ready|live) HTTP/\\d\\.\\d\"\\s+200\\s+OK"
      }]
    }]
  proxy.istio.io/config: |-
    proxyMetadata:
      ISTIO_META_IDLE_TIMEOUT: 0s
podLabels:
  admission.datadoghq.com/enabled: "true"

image:
  name: acapy-cloud/endorser
  pullPolicy: Always
  tag: master

initContainers:
  - name: nc-nats
    image: busybox
    command: ['sh', '-c', 'until nc -z nats 4222; do echo waiting for nats; sleep 2; done;']
  - name: nats-check
    image: bitnami/natscli
    command:
      - sh
      - -c
      - |
        until nats --server $NATS_SERVER str info $NATS_STREAM >/dev/null 2>&1; do echo waiting for nats stream; sleep 2; done;
    env:
      - name: NATS_SERVER
        value: "{{ .Values.env.NATS_SERVER }}"
      - name: NATS_STREAM
        value: "{{ .Values.env.NATS_STREAM }}"

command:
  - poetry
  - run
  - uvicorn
  - endorser.main:app
  - --log-config=/tmp/log_conf.yaml
  - --workers
  - 1
  - --host
  - 0.0.0.0
  - --port
  - 3009

service:
  name: endorser
  port: 3009
  containerPort: 3009
  appProtocol: http

livenessProbe:
  httpGet:
    path: /health/live
    port: endorser
readinessProbe:
  httpGet:
    path: /health/ready
    port: endorser

autoscaling:
  enabled: false

# resources:
#   requests:
#     cpu: 50m
#     memory: 128Mi
#   limits:
#     cpu: 250m
#     memory: 256Mi

secretData:
  ACAPY_GOVERNANCE_AGENT_API_KEY: adminApiKey

env:
  LOG_LEVEL: info
  PYTHONPATH: /

  ACAPY_GOVERNANCE_AGENT_URL: http://governance-agent:3021

  # Trust registry
  TRUST_REGISTRY_URL: http://trust-registry:8000

  GOVERNANCE_ACAPY_LABEL: Governance
  ENABLE_SERIALIZE_LOGS: "TRUE"

  NATS_CREDS_FILE: ""
  NATS_SERVER: nats://nats:4222
  NATS_SUBJECT: cloudapi.aries.events
  NATS_STREAM: cloudapi_aries_events
  ENDORSER_DURABLE_CONSUMER: endorser

podSecurityContext:
  fsGroup: 65534
securityContext:
  runAsUser: 65534

extraVolumes:
  - name: logs
    emptyDir: {}
extraVolumeMounts:
  - name: logs
    mountPath: /logs

podAntiAffinityPreset: soft
nodeAffinityPreset:
  type: soft
  key: node.kubernetes.io/lifecycle
  values:
    - spot

configFiles:
  log_conf.yaml:
    path: /tmp/log_conf.yaml
    content: |-
      version: 1
      disable_existing_loggers: False
      formatters:
        default:
          "()": uvicorn.logging.DefaultFormatter
          format: '%(asctime)s %(name)s %(levelname)s %(message)s'
          use_colors: null
        access:
          "()": uvicorn.logging.AccessFormatter
          format: '%(asctime)s %(name)s %(levelname)s %(client_addr)s - "%(request_line)s" %(status_code)s'
      handlers:
        default:
          formatter: default
          class: logging.StreamHandler
          stream: ext://sys.stderr
        access:
          formatter: access
          class: logging.StreamHandler
          stream: ext://sys.stdout
      loggers:
        uvicorn:
          level: INFO
          handlers:
            - default
          propagate: no
        uvicorn.error:
          level: INFO
        uvicorn.access:
          level: INFO
          handlers:
            - access
          propagate: no
