replicaCount: 1

daemon: false

image:
  repository: "324190738845.dkr.ecr.af-south-1.amazonaws.com/governance-multitenant-agent"
  pullPolicy: Always
  tag: "pr-7"

args:
  - --wallet-type
  - askar
  - --auto-promote-author-did
  - --plugin
  - acapy_wallet_groups_plugin

ingress:
  internal:
    enabled: true
    className: nginx-internal
    annotations:
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: mt-agent.cloudapi.dev.didxtech.com
        paths:
          - path: /
            port: 4020
  external:
    enabled: true
    className: nginx-external
    annotations:
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: mt-agent.cloudapi.dev.didxtech.com
        paths:
          - path: /
            port: 4020
  internal-e2e:
    enabled: false
    className: nginx-internal
    annotations:
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: governance-mt-agent.cloudapi.dev.didxtech.com
        paths:
          - path: /
            port: 4021

service:
  # if set, will run Pods on Node Network
  hostNetwork: false
  port: 4021
  containerPort: 3021

addPorts:
  - port: 4020
    containerPort: 3020
    protocol: TCP

httpProbes:
  liveness:
    path: /status/live
    initialDelaySeconds: 300
    timeoutSeconds: 30
  readiness:
    path: /status/ready
    initialDelaySeconds: 5
    timeoutSeconds: 30

persistence:
  enabled: false

autoscaling:
  enabled: false

extraSecretNamesForEnvFrom:
  - didx-multitenant-rds-credentials
  - mt-agent-env

# Sensitive environment variables are sourced from k8s secrets:
# - generated with secretData, or
# - pre-populated with external tooling
# TODO: Helm secret logic to create new secret if not exist
secretData{}:
  # WALLET_DB_HOST: "governance-ga-wallets-db"
  # WALLET_DB_PORT: "5432"
  # ACAPY_LABEL: "Alice"
  # ACAPY_WALLET_NAME: "Alive_name"
  # ACAPY_WALLET_KEY: "alice_key"
  # ACAPY_ADMIN_API_KEY: "adminApiKey"
  # ACAPY_MULTITENANT_JWT_SECRET: "jwtSecret"
  # ACAPY_TENANT_AGENT_API_KEY: "adminApiKey"
  # ACAPY_GOVERNANCE_AGENT_API_KEY: "adminApiKey"
  # ACAPY_WALLET_STORAGE_CONFIG: '{"url":"aries-default-multitenant.ce5tswq1klfu.af-south-1.rds.amazonaws.com:5432","wallet_scheme":"MultiWalletSingleTable"}'

env:
  # for aca-py
  HTTP_PORT: 3020
  WEBHOOK_PORT: 3010
  ADMIN_PORT: 3021
  ADMIN_URL: http://governance-multitenant-agent:4021
  ACAPY_OUTBOUND_TRANSPORT: http
  ACAPY_ADMIN: "[0.0.0.0,3021]"
  ACAPY_ENDPOINT: https://mt-agent.cloudapi.dev.didxtech.com
  ACAPY_WEBHOOK_URL: http://governance-webhooks-web:3010/multitenant
  # Tails server
  ACAPY_TAILS_SERVER_BASE_URL: http://tails-server:6543

  ACAPY_WALLET_TYPE: askar
  ACAPY_WALLET_STORAGE_TYPE: postgres_storage
  ACAPY_LOG_LEVEL: debug
  ACAPY_AUTO_PROVISION: true
  # Ledger
  ACAPY_GENESIS_URL: http://ledger-nodes:9000/genesis
  # Multi-tenant Configuration
  ACAPY_MULTITENANT: true
  ACAPY_MULTITENANT_ADMIN: false
  ACAPY_PUBLIC_INVITES: true
  AGENT_ENDPOINT: https://mt-agent.cloudapi.dev.didxtech.com
  # ## DO NOT CHANGE VARIABLES BELOW
  # ## Unless you know exactly what you are doing
  # ## Changes will probably break CloudAPI
  # Optional Helper Configurations - See https://github.com/hyperledger/aries-cloudagent-python/blob/main/aries_cloudagent/config/argparse.py
  ACAPY_AUTO_ACCEPT_INVITES: false
  ACAPY_AUTO_ACCEPT_REQUESTS: false
  ACAPY_AUTO_PING_CONNECTION: true
  ACAPY_AUTO_RESPOND_MESSAGES: false
  ACAPY_AUTO_RESPOND_CREDENTIAL_PROPOSAL: false
  ACAPY_AUTO_RESPOND_CREDENTIAL_OFFER: false
  ACAPY_AUTO_RESPOND_CREDENTIAL_REQUEST: false
  ACAPY_AUTO_RESPOND_PRESENTATION_PROPOSAL: false
  ACAPY_AUTO_RESPOND_PRESENTATION_REQUEST: false
  ACAPY_AUTO_STORE_CREDENTIAL: true
  ACAPY_AUTO_VERIFY_PRESENTATION: true
  ACAPY_PRESERVE_EXCHANGE_RECORDS: true
  # Endorser
  ACAPY_ENDORSER_ROLE: author
  ACAPY_AUTO_REQUEST_ENDORSEMENT: true
  ACAPY_AUTO_WRITE_TRANSACTIONS: true
  ACAPY_ENDORSER_ALIAS: endorser
