replicaCount: 1

daemon: false

image:
  repository: "324190738845.dkr.ecr.af-south-1.amazonaws.com/governance-webhooks-web"
  pullPolicy: Always
  tag: "baseline-04d67c5"

ingress:
  enabled: false
  tls_enabled: false

service:
  # if set, will run Pods on Node Network
  hostNetwork: false
  port: 3010
  containerPort: 3010

httpProbes: {}
 # liveness:
 #   path: /
 # readiness:
 #   path: /
 # initialDelaySeconds: 2

persistence:
  enabled: false

configFiles:
  shared_models.py:
    path: /app/shared_models/shared_models.py
    content: |-
      {{ .Files.Get "assets/shared_models/shared_models.py" }}
  __init__.py:
    path: /app/shared_models/__init__.py
    content: |-
      {{ .Files.Get "assets/shared_models/__init__.py" }}

autoscaling:
  enabled: false

nodeSelector:
  eks.amazonaws.com/nodegroup: application

env:
  REDIS_HOST: aries-default.gpip5x.0001.afs1.cache.amazonaws.com:6379
  ACAPY_WEBHOOK_PORT: 3010
  LOG_LEVEL: error
  OPENAPI_NAME: Webhooks
