{{- if .Values.secretData }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "acapy-cloud.fullname" . }}-env
  labels:
    {{- include "acapy-cloud.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secretData }}
  {{ upper (snakecase $key) }}: {{ tpl (toString $value) $ | quote }}
  {{- end }}
{{- end }}
